### ISSUE TITLE
Support drag/drop of assets from asset selector

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/franklin-assets-selector#31]
Improve user experience. Provide ability to drag/drop assets from asset selector (AS) to word docs.

**Comment by mfrisbey** [comment]
I was experimenting with the asset selector's [rail mode](https://cq-dev.slack.com/archives/C05KMBFQNTD/p1692219557627929), and its asset selection experience is strictly drag/drop. Out-of-the-box, I can drag assets from the selector, but I'm unable to drop them on a Word document. I assume that in the "drag" event, we need to populate the payload with something that can be dropped in Word.

Here is a working prototype: https://github.com/mfrisbey/franklin-tutorial/tree/08782c367e3eec7615c847d572ae757be93c6cd5

**Comment by tmathern** [comment]
For now, going the copy/paste way, as this use case hits technical limitations with drag and drop between iframes if we don't control all iframes.
