### ISSUE TITLE
Support AEM's AMS and On-prem flavors for use with Franklin

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/franklin-assets-selector#32]
Support integration with AEM 6.x (AMS/OnPrem). Pre-requisite is to have AS working with AEM 6.x versions. How to deliver assets from AEM Asset delivery needs to be figured out. Copying over to mediabus is definitely an option.

**Comment by n-zimmermann** [comment]
not an immediate priority. A maybe item for later.
