### ISSUE TITLE
Add new CORS configuration to AEM

### ISSUE THREAD

**Issue by mfrisbey** [hlxsites/franklin-assets-selector#45]
In order for the assets panel to communicate with AEM, it will need to be allowed by AEM's CORS policy. The policy itself could be very similar to the [asset selector's](https://git.corp.adobe.com/CQ/quickstart/blob/326830a497e0fa55556ab1f7f50a223f0a068dfc/src/main/features/common/author/base-granite-model_quickstart_author.json#L134) (the panel wouldn't need write capabilities, which would make the policy even more secure).

There are a couple of options:

* We could require our customers to add the policy before they can use the panel.
* Modify the quickstart so that it includes the policy for all customers. This would be the more convenient experience for our users, but would require a change in the quickstart.

Because the policies are based on the origin, this would be another problem that #38 could solve by hosting the panel on a single URL. This would allow us to tighten the policy to only allow one host, instead of wildcarding it to include all `hlx.page/live` URLs (which would be much less secure).

**Comment by tmathern** [comment]
Closing this for now. As the version hosted with the MFE is making progress, we may not need to do CORS policy changes in AEM.
