### ISSUE TITLE
Asset Selector Rail View does not work with multiple repo access

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/franklin-assets-selector#56]
[Related conversation](https://cq-dev.slack.com/archives/C05KMBFQNTD/p1692796569637379)

**Comment by sdmcraft** [comment]
Being handled in https://git.corp.adobe.com/CQ/assets-selectors/pull/192

**Comment by mfrisbey** [comment]
I added a comment to the PR, but using `rail: true` instead of `hideTreeNav: true` makes it so that the environment selector appears. We merged a change today to use `rail` instead of `hideTreeNav`.

**Comment by sdmcraft** [comment]
Likely fixed via https://git.corp.adobe.com/CQ/assets-selectors/pull/212
