### ISSUE TITLE
Assets Selector Extension - For summit demo

### ISSUE THREAD

**Issue by shrotia** [hlxsites/franklin-assets-selector#67]
1. Have custom blockName for the Videos
2. Copy Link of the image in the clipboard instead of Binary

**Comment by sdmcraft** [comment]
This done.
[Custom block name.](https://www.aem.live/developer/configuring-aem-assets-sidekick-plugin#blockname)
[Copy by reference](https://www.aem.live/developer/configuring-aem-assets-sidekick-plugin#copymode)
